
ALTER TABLE chatbot_sessions 
ADD COLUMN IF NOT EXISTS questions JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS question_index INTEGER DEFAULT 0;

COMMENT ON COLUMN chatbot_sessions.questions IS 'Array of 3 category-specific questions generated by LLM';
COMMENT ON COLUMN chatbot_sessions.question_index IS 'Current question index (0-2), increments after each answer';
